# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89dde1e6efaf50856432e5db48ffea4b0c968bb17bfede0a94d8e9c8d22adff4bb50657ff15a004a599aaf833a07959e599fe9eaa20afc6f569e65c1f60ed959

test:
  secret_key_base: 3f5a2fc7e3228502749a421de3d326e312aee419da70d7f08d9e3e0e62de9ceb144473bf3bebb3db2860263bc6938d0955c4a2e3ce5a0e869d39272fddc27e3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
